### ISSUE TITLE
MetaChain Container Sanity Workflow

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/metachain#131]
#### What would you like to be added:

For `.github/workflows/release-docker.yml`, we need to ensure the workflow released can run on all silicon architecture. This also acts as a set of sanity tests to ensure each docker image can be run after building. 

We should do this in jest and call it `packages/testsuite-docker-sanity`.

#### Why is this needed:

Shift left workflow for https://github.com/DeFiCh/metachain/issues/61 and https://github.com/DeFiCh/metachain/issues/62

---

/triage accepted
/assign @fuxingloh

**Comment by mambisi** [comment]
@fuxingloh , I looked for multiple solution, the best is using  https://github.com/pguyot/arm-runner-action for testing arm builds but its using an arm vm under the hood. for real, testing we have to use a self-hosted runner similar to what defichain is using to test on multiple platform. refer to  https://github.com/actions/runner-images/issues/2552 has discussion on `buildx` and `qemu` on GitHub actions

**Comment by fuxingloh** [comment]
Hmm. Let's wait for the official support of non-self-hosted arm-runners from GitHub.

For now, let's just do basic Container testing for builds in `@defimetachain/testsuite-docker-sanity` via a different OS first.

```yml
jobs:
  sanity:
    name: Testsuite Docker Sanity
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
```
